[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/settings.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Light" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Light" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Light" }
# "GeistMono Nerd Font Mono"
# "JetBrainsMono Nerd Font Mono"
# "MonoLisa Nerd Font Mono"
# "SFMono Nerd Font Mono"
# "MesloLGM Nerd Font Mono"
# "CaskaydiaCove Nerd Font"
# "CaskaydiaMono Nerd Font"
# "FiraCode Nerd Font Mono"

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "None"
option_as_alt = "Both"
opacity = 0.95

[window.padding]
x = 10
y = 10
